### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [Atos20/mod_0_skills#1]
@Atos20 overall, nice work on the assessment. Because you've been in good standing up until this point on assignments, I'd like to give you the opportunity to make some changes to your assessment, before we declare you `technical ready`:
* [x] Please update part 3 (make sure that you're testing your code in the js console.
  * here are the directions: https://fierce-beyond-34376.herokuapp.com/confirmation
* [x] In part 2, Make sure that any variables that store a collection are named plurally
* [x] Make sure that your class names are singular and PascalCase
* [x] Since each of your classes are Restaurants, make sure that your attribute and method names are from the perspective of the restaurant.
  * ie. your class 2 `hire` method is a good name that matches this rule, but many seem like they're from the customer perspective.

**Comment by Atos20** [comment]
@damwhit 

Hi David, it is nice to hear from you again. I know I had made some mistakes during the assessment and I appreciate the opportunity. I have finished updating the assessment. Please let me know if you require any additional information from me.

**Comment by Atos20** [comment]
@damwhit I also want to thank for your help, guidance, and mentoring through Mod 0. I learned a lot from you and Ellen. Keep it up and I hope everything is going well in Japan!

**Comment by damwhit** [comment]
@Atos20 thanks for going back and making these updates. You are officially `technical ready`! I love that you utilized many console logs to see if your javascript was working correctly. Definitely keep that up!
